test:
	# Test 1 for project 3.1: Compare the output of the linker with the expected output,
	python3 linker.py tests/main.lk && diff -U 3 newobj tests/cmp_test1 && echo "Test 1 passed" || echo "Test 1 failed"
